name: dotnet package

on: [push]

env:
  PROJECT_PATH:  StarGarden/StarGarden.csproj
  ARTIFACT_PATH: /workspace/Kimiestar/StarGarden/StarGarden/bin/Release/net7.0-windows10.0.22621.0/win-x64/publish/StarGarden.exe

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Setup .NET Core SDK 7.0.400
        uses: https://github.com/actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.400
      - name: Install dependencies
        run: dotnet restore ${{env.PROJECT_PATH}}
      - name: Build
        run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore  
      - name: Publish
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release -r win-x64 --no-self-contained -p:PublishSingleFile=true -p:UseAppHost=true
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload windows binaries
        uses: actions/upload-artifact@v3
        with:
            name: StarGarden.exe
            path: ${{env.ARTIFACT_PATH}} 